name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: quay.io/prometheus/golang-builder

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Upload a Build Artifact
    - uses: actions/upload-artifact@v4.3.6
      with:
        path: ./sql_exporter
